### PR TITLE
Config with default template 3f6d9cbf

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Comment by jensens** [comment]
@gforcada what is the magic spell to get the shared workflow from plone/meta in here? 
("Expectus workflowus" did not work)

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
Yeah, I'm starting to not like it that much, is a bit hidden:

You have to go to https://github.com/organizations/plone/settings/actions scroll all the way down and on the three dots on the `Testing` required workflow, select update, on the next screen search for the repository and save 🪄 

For pre-commit.ci you need to go to https://results.pre-commit.ci/ and add it as well.

Done it already 😄

**Review by gforcada — APPROVED** [review]

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
